name: Debug CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug directory structure
        run: ls -R

      - name: Debug changed files
        run: git diff --name-only HEAD^ HEAD