name: Backend CI
on:
  push:
    branches: [main]
    paths: ["backend/**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Django
        run: |
          docker build -t evaander/your-app-django:latest -f backend/admin/Dockerfile backend/admin
          docker push evaander/your-app-django:latest

      - name: Build and push Flask
        run: |
          docker build -t evaander/your-app-flask:latest -f backend/main/Dockerfile backend/main
          docker push evaander/your-app-flask:latest

      - name: Update GitOps
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://${GITHUB_TOKEN}@github.com/CooBRA01/app-gitops.git
          cd app-gitops
          sed -i "s|your-app-django:.*|your-app-django:latest|" manifests/django-deployment.yaml
          sed -i "s|your-app-flask:.*|your-app-flask:latest|" manifests/flask-deployment.yaml
          git add .
          git commit -m "Update backend images to latest"
          git push
