name: Backend CI

on:
  push:
    branches: [main]
    paths:
      - 'admin/**'  
      - 'main/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set environment variables
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Debug - show directory structure
        run: ls -R

      - name: Debug - show changed files
        run: git diff --name-only HEAD^ HEAD || echo "No parent commit available"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Django image
        run: |
          docker build -t evaander/your-app-django:${{ env.IMAGE_TAG }} -f admin/Dockerfile admin
          docker push evaander/your-app-django:${{ env.IMAGE_TAG }}

      - name: Build and push Flask image
        run: |
          docker build -t evaander/your-app-flask:${{ env.IMAGE_TAG }} -f main/Dockerfile main
          docker push evaander/your-app-flask:${{ env.IMAGE_TAG }}

      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: COOBRA01/app-gitops
          token: ${{ secrets.TOKEN }}
          path: app-gitops

      - name: Update GitOps manifests
        run: |
          cd app-gitops
          
          sed -i "s|image: evaander/your-app-django:.*|image: evaander/your-app-django:${{ env.IMAGE_TAG }}|" manifests/django-deployment.yml
          sed -i "s|image: evaander/your-app-flask:.*|image: evaander/your-app-flask:${{ env.IMAGE_TAG }}|" manifests/flask-deployment.yml
          
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update backend images to ${{ env.IMAGE_TAG }}"
            git push
          fi
