name: Backend CI

on:
  push:
    branches: [main]
    paths:
      - 'backend/admin/**'  # Match Django files
      - 'backend/main/**'   # Match Flask files

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug directory structure
        run: ls -R

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Django
        run: |
          docker build -t evaander/your-app-django:latest -f backend/admin/Dockerfile backend/admin
          docker push evaander/your-app-django:latest
        working-directory: .

      - name: Build and push Flask
        run: |
          docker build -t evaander/your-app-flask:latest -f backend/main/Dockerfile backend/main
          docker push evaander/your-app-flask:latest
        working-directory: .

      - name: Update GitOps
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://x:${GITHUB_TOKEN}@github.com/CooBRA01/app-gitops.git
          cd app-gitops
          sed -i "s|evaander/your-app-django:.*|evaander/your-app-django:latest|" manifests/django-deployment.yaml
          sed -i "s|evaander/your-app-flask:.*|evaander/your-app-flask:latest|" manifests/flask-deployment.yaml
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update backend images to latest" || echo "No changes to commit"
          git push